# coding: utf-8

"""
    Version 3 of CANDY HOUSE’s Sesame API

    We use RESTful API to provide basic manipulation of the Sesame smart lock, including: * Get Sesame lock/unlock status * Get battery status * Lock and unlock Sesame * Sync Sesame status * Get results for lock, unlock, and sync commands   # noqa: E501

    OpenAPI spec version: 3.0.0
    Contact: sesame@candyhouse.co
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import sesame_client
from sesame_client.api.default_api import DefaultApi  # noqa: E501
from sesame_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = sesame_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_action_result_get(self):
        """Test case for action_result_get

        Query Execution Result  # noqa: E501
        """
        pass

    def test_sesame_device_id_get(self):
        """Test case for sesame_device_id_get

        Get Sesame status  # noqa: E501
        """
        pass

    def test_sesame_device_id_post(self):
        """Test case for sesame_device_id_post

        Control Sesame  # noqa: E501
        """
        pass

    def test_sesames_get(self):
        """Test case for sesames_get

        Get Sesame list  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
