# coding: utf-8

# flake8: noqa

"""
    Version 3 of CANDY HOUSE’s Sesame API

    We use RESTful API to provide basic manipulation of the Sesame smart lock, including: * Get Sesame lock/unlock status * Get battery status * Lock and unlock Sesame * Sync Sesame status * Get results for lock, unlock, and sync commands   # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Contact: sesame@candyhouse.co
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

__version__ = "1.0.0"

# import apis into sdk package
from sesame_client.api.default_api import DefaultApi

# import ApiClient
from sesame_client.api_client import ApiClient
from sesame_client.configuration import Configuration
from sesame_client.exceptions import OpenApiException
from sesame_client.exceptions import ApiTypeError
from sesame_client.exceptions import ApiValueError
from sesame_client.exceptions import ApiKeyError
from sesame_client.exceptions import ApiException
# import models into sdk package
from sesame_client.models.bad_request_response import BadRequestResponse
from sesame_client.models.control_sesame_request import ControlSesameRequest
from sesame_client.models.control_sesame_response import ControlSesameResponse
from sesame_client.models.get_sesame_response import GetSesameResponse
from sesame_client.models.get_sesame_status_response import GetSesameStatusResponse
from sesame_client.models.query_execution_result_response import QueryExecutionResultResponse

