# coding: utf-8

"""
    Version 3 of CANDY HOUSE’s Sesame API

    We use RESTful API to provide basic manipulation of the Sesame smart lock, including: * Get Sesame lock/unlock status * Get battery status * Lock and unlock Sesame * Sync Sesame status * Get results for lock, unlock, and sync commands   # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Contact: sesame@candyhouse.co
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class BadRequestResponse(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'error': 'str'
    }

    attribute_map = {
        'error': 'error'
    }

    def __init__(self, error=None):  # noqa: E501
        """BadRequestResponse - a model defined in OpenAPI"""  # noqa: E501

        self._error = None
        self.discriminator = None

        self.error = error

    @property
    def error(self):
        """Gets the error of this BadRequestResponse.  # noqa: E501

        `BAD_PARAMS` Your request paremeters are invalid `CLOUD_INTEGRATION_NOT_ENABLED` Please enable cloud integration in Sesame app under Sesame > Change Settings. `LOW_BATTERY` Your device cannot be operated because its batteries are low. `DEVICE_IS_BUSY` Your device cannot be operated because it is occupied by other requests. `DEVICE_IS_BUSY :seconds` Your device cannot be operated because the device is occupied by other requests. The :seconds is an integer indicating the max duration you have to wait until you can send the next request.   # noqa: E501

        :return: The error of this BadRequestResponse.  # noqa: E501
        :rtype: str
        """
        return self._error

    @error.setter
    def error(self, error):
        """Sets the error of this BadRequestResponse.

        `BAD_PARAMS` Your request paremeters are invalid `CLOUD_INTEGRATION_NOT_ENABLED` Please enable cloud integration in Sesame app under Sesame > Change Settings. `LOW_BATTERY` Your device cannot be operated because its batteries are low. `DEVICE_IS_BUSY` Your device cannot be operated because it is occupied by other requests. `DEVICE_IS_BUSY :seconds` Your device cannot be operated because the device is occupied by other requests. The :seconds is an integer indicating the max duration you have to wait until you can send the next request.   # noqa: E501

        :param error: The error of this BadRequestResponse.  # noqa: E501
        :type: str
        """
        if error is None:
            raise ValueError("Invalid value for `error`, must not be `None`")  # noqa: E501

        self._error = error

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BadRequestResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
